aci:
    race.ini:
        RACE:
            TRACK: "monza"
            CONFIG_TRACK: ""
        SESSION_0:
            SPAWN_SET: HOTLAP_START
    video.ini:
        VIDEO:
            WIDTH: 1280
            HEIGHT: 736
    controls.ini:
        X360:
            SPEED_SENSITIVITY: 0.2
    assists.ini:
        ASSISTS:
            TYRE_BLANKETS: 1
    capture:
        is_docker: False
        is_proton: True
        images:
            image_format: "BGR0"
            wait_for_new_frames: False
        state:
            use_dicts: True
    termination:
        check_every_n: 1000
        max_consecutive_failures: 3