import numpy as np

MINIMUM_SPEED_KMH = 3.6
SAMPLING_FREQUENCY = 25  # Hz
RESTART_PATIENCE = 10 * SAMPLING_FREQUENCY

PEDAL_MIN = 0.0
PEDAL_MAX = 1.0
# rate per second * control frequency
PEDAL_RATE = 1200 / 100 * 1 / SAMPLING_FREQUENCY

STEERING_MIN = -1.0
STEERING_MAX = 1.0
STEERING_RATE = 600 / 180 * 1 / SAMPLING_FREQUENCY


CONTROL_RATES = np.array([STEERING_RATE, PEDAL_RATE, PEDAL_RATE])
CONTROL_MINS = np.array([STEERING_MIN, PEDAL_MIN, PEDAL_MIN])
CONTROL_MAXS = np.array([STEERING_MAX, PEDAL_MAX, PEDAL_MAX])

MAX_EPISODE_TIME_S = 600
MAX_EPISODE_LENGTH = SAMPLING_FREQUENCY * MAX_EPISODE_TIME_S
